'use strict';

const express = require('express');
const log = require('../utils/logger');
const registry = require('../models/registry');

const router = express.Router();
const logger = log.child('show');

function redactHeaders(headers) {
  const redacted = {};
  for (const [key, value] of Object.entries(headers || {})) {
    const normalizedKey = String(key).toLowerCase();
    if (['authorization', 'proxy-authorization', 'x-api-key', 'x_api_key'].includes(normalizedKey)) {
      redacted[key] = '***REDACTED***';
    } else {
      redacted[key] = value;
    }
  }
  return redacted;
}

function summarizeBody(body) {
  if (!body || typeof body !== 'object') {
    return body;
  }

  const summary = Array.isArray(body) ? [] : {};
  for (const [key, value] of Object.entries(body)) {
    if (key === 'images' && Array.isArray(value)) {
      summary[key] = `[${value.length} image(s)]`;
      continue;
    }

    if (typeof value === 'string' && value.length > 500) {
      summary[key] = `${value.slice(0, 500)}... [truncated ${value.length - 500} chars]`;
      continue;
    }

    summary[key] = value;
  }
  return summary;
}

function getModelCapabilities(cfg) {
  if (Array.isArray(cfg.capabilities) && cfg.capabilities.length > 0) {
    return cfg.capabilities.map(capability => String(capability));
  }

  const capabilities = ['completion', 'tools'];
  if (cfg.supports_vision) {
    capabilities.push('vision');
  }
  return capabilities;
}

// ── POST /api/show ───────────────────────────────────────────
router.post('/', (req, res) => {
  logger.info('show request context %s', JSON.stringify({
    requestId: req.requestId,
    method: req.method,
    path: req.originalUrl,
    contentType: req.headers['content-type'] || '',
    contentLength: req.headers['content-length'] || '',
    ip: req.headers['x-forwarded-for'] || req.ip || req.socket?.remoteAddress || '',
    headers: redactHeaders(req.headers),
    query: req.query || {},
    params: req.params || {},
    body: summarizeBody(req.body),
    rawBody: typeof req.rawBody === 'string' ? (req.rawBody.length > 1000
      ? `${req.rawBody.slice(0, 1000)}... [truncated ${req.rawBody.length - 1000} chars]`
      : req.rawBody) : undefined,
  }));

  const fallbackModel = registry.list()[0];

  // Ollama API 使用 "model" 参数；一些客户端会先发空 body 做能力探测
  const name = req.body.model || req.body.name || fallbackModel?.name;
  if (!name) {
    logger.warn(`缺少 model 参数且没有可回退模型，请求体: ${JSON.stringify(req.body)}`);
    return res.status(400).json({ error: '"model" is required', request: req.body });
  }

  if (!req.body.model && !req.body.name) {
    logger.info('show request missing model, falling back to configured model %s', name);
  }

  const model = registry.get(name);
  if (!model) return res.status(404).json({ error: `model "${name}" not found` });

  const cfg = registry.resolve(model);
  const family = cfg.family || model.provider || 'unknown';
  const upstreamModel = cfg.upstream_model || cfg.model_id || model.model_id || model.name;

  res.json({
    license:    '',
    modelfile:  cfg.modelfile || `# Modelfile generated by ollama-proxy\nFROM ${model.name}\n`,
    parameters: '',
    template:   '',
    details: {
      parent_model:       '',
      format:             'proxy',
      family,
      families:           Array.isArray(cfg.families) && cfg.families.length > 0 ? cfg.families : [family],
      parameter_size:     cfg.parameter_size || 'unknown',
      quantization_level: cfg.quantization_level || cfg.quantization || 'proxy',
    },
    model_info: {
      'general.architecture':    family,
      'general.parameter_count': Number(cfg.parameter_count || 0),
      ...(cfg.context_length || cfg.context_size ? {
        [`${family}.context_length`]: Number(cfg.context_length || cfg.context_size),
      } : {}),
      ...(cfg.embedding_length ? {
        [`${family}.embedding_length`]: Number(cfg.embedding_length),
      } : {}),
    },
    capabilities: getModelCapabilities(cfg),
    modified_at: new Date().toISOString(),
    model:       `${model.name}:latest`,
    name:        `${model.name}:latest`,
    remote_model: upstreamModel,
    remote_host:  cfg.base_url || '',
    size:        cfg.size || 0,
    digest:      String(cfg.digest || upstreamModel || 'unknown'),
  });
});

module.exports = router;
